# -*- coding: utf-8 -*-
"""Project_759_TeamINFO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pC4wFPs1oRpm-ysZrW62wwgPzDxVOHQQ
"""

# MapQuest Test
routes = {
    ("sydney", "newcastle"): {"distance": "160 km", "time": "2 hours"},
    ("sydney", "wollongong"): {"distance": "85 km", "time": "1.5 hours"},
    ("sydney", "canberra"): {"distance": "290 km", "time": "3.5 hours"},
    ("sydney", "melbourne"): {"distance": "875 km", "time": "9 hours"},
}

def get_route(start, end):
    start, end = start.lower(), end.lower()
    if (start, end) in routes:
        return routes[(start, end)]
    else:
        return {"error": "Sorry, route not available in NSW/Australia dataset."}

#Interaction
print("Welcome to the NSW Route Planner!")
start = input("Enter your current location: ")
end = input("Enter your destination: ")

result = get_route(start, end)

if "error" in result:
    print(result["error"])
else:
    print(f"Distance: {result['distance']}, Estimated Time: {result['time']}")